# Generated by Django 2.1.5 on 2019-02-04 17:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog_news',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 4, 19, 43, 45, 271093)),
        ),
        migrations.AlterField(
            model_name='blog_news',
            name='published_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='date published'),
        ),
    ]
