# Generated by Django 2.1.5 on 2019-02-18 17:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20190204_1943'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog_news',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='img/'),
        ),
        migrations.AlterField(
            model_name='blog_news',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 18, 19, 57, 11, 733142)),
        ),
    ]
