# Generated by Django 2.1.5 on 2019-03-18 18:01

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_auto_20190218_1957'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=50)),
                ('category_summury', models.CharField(max_length=200)),
                ('url_slug', models.CharField(max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='blog_news',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 18, 20, 1, 26, 292411)),
        ),
        migrations.AddField(
            model_name='blog_news',
            name='news_category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='mainapp.Categories'),
        ),
    ]
