# Generated by Django 2.1.5 on 2019-03-18 18:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_auto_20190318_2001'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog_news',
            name='url_slug',
            field=models.CharField(default='default', max_length=30),
        ),
        migrations.AlterField(
            model_name='blog_news',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 18, 20, 9, 40, 192561)),
        ),
    ]
