# Generated by Django 2.1.5 on 2019-03-18 18:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_auto_20190318_2009'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog_news',
            old_name='url_slug',
            new_name='url_slug_news',
        ),
        migrations.AlterField(
            model_name='blog_news',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 18, 20, 11, 52, 373405)),
        ),
    ]
